In [1]:
import pandas as pd
import numpy as np

In [2]:
red_wine=pd.read_csv('Datasets/winequality-red.csv')
red_wine.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur,total_sulfur,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [3]:
X=red_wine.iloc[:,:11]
y=red_wine['quality']

In [4]:
# getting mean of X features
for i in range(len(X)):
    X['tag']=((X['fixed_acidity']+X['volatile_acidity']+X['citric_acid']+X['residual_sugar']+X['chlorides']+
              X['free_sulfur']+X['total_sulfur']+X['density']+X['pH']+X['sulphates']+X['alcohol'])/11)
    
X.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur,total_sulfur,density,pH,sulphates,alcohol,tag
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,6.322164
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,10.732255
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,8.609000
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,9.595727
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,6.322164

In [5]:
X_data=np.array(X['tag'])
y_data=np.array(y)

In [6]:
def mean(array):
    sum=0
    for i in array:
        sum+=i
    return (sum/len(array))

In [7]:
def best_fit_slope(xs,ys):
    m=(((mean(xs)*mean(ys)) - mean(xs*ys)) / ((mean(xs)**2) - mean(xs**2)))
    b=mean(ys)-m*mean(xs**2)
    return m,b

In [8]:
def train_test_split(xs,ys):
    test_size=0.2
    X_train=xs[:-int(test_size*len(xs))]
    X_test=xs[-int(test_size*len(xs)):]
    y_train=ys[:-int(test_size*len(ys))]
    y_test=ys[-int(test_size*len(ys)):]
    return X_train, X_test, y_train, y_test

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X_data,y_data)

In [10]:
m,b=best_fit_slope(X_train,y_train)

In [11]:
def predict(xs):
    y_predict=((m*xs)+b)
    print(y_predict)

In [12]:
# testing
predict(6.0)

8.491295202455133